config/routes.rb
Gatos::Application.routes.draw do
  resources :gatos

end

app/models/gato.rb
class Gato < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gatos_controller.rb
class GatosController < ApplicationController
  # GET /gatos
  # GET /gatos.json
  def index
    @gatos = Gato.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gatos }
    end
  end

  # GET /gatos/1
  # GET /gatos/1.json
  def show
    @gato = Gato.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gato }
    end
  end

  # GET /gatos/new
  # GET /gatos/new.json
  def new
    @gato = Gato.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gato }
    end
  end

  # GET /gatos/1/edit
  def edit
    @gato = Gato.find(params[:id])
  end

  # POST /gatos
  # POST /gatos.json
  def create
    @gato = Gato.new(params[:gato])

    respond_to do |format|
      if @gato.save
        format.html { redirect_to @gato, notice: 'Gato was successfully created.' }
        format.json { render json: @gato, status: :created, location: @gato }
      else
        format.html { render action: "new" }
        format.json { render json: @gato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gatos/1
  # PUT /gatos/1.json
  def update
    @gato = Gato.find(params[:id])

    respond_to do |format|
      if @gato.update_attributes(params[:gato])
        format.html { redirect_to @gato, notice: 'Gato was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gatos/1
  # DELETE /gatos/1.json
  def destroy
    @gato = Gato.find(params[:id])
    @gato.destroy

    respond_to do |format|
      format.html { redirect_to gatos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gatos_helper.rb
module GatosHelper
end

app/views/gatos/_form.html.erb
<%= form_for(@gato) do |f| %>
  <% if @gato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gato.errors.count, "error") %> prohibited this gato from being saved:</h2>

      <ul>
      <% @gato.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :comentario %><br />
    <%= f.text_area :comentario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gatos/edit.html.erb
<h1>Editing gato</h1>

<%= render 'form' %>

<%= link_to 'Show', @gato %> |
<%= link_to 'Back', gatos_path %>

app/views/gatos/index.html.erb
<h1>Listing gatos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Comentario</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gatos.each do |gato| %>
  <tr>
    <td><%= gato.nombre %></td>
    <td><%= gato.comentario %></td>
    <td><%= link_to 'Show', gato %></td>
    <td><%= link_to 'Edit', edit_gato_path(gato) %></td>
    <td><%= link_to 'Destroy', gato, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gato', new_gato_path %>

app/views/gatos/new.html.erb
<h1>New gato</h1>

<%= render 'form' %>

<%= link_to 'Back', gatos_path %>

app/views/gatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @gato.nombre %>
</p>

<p>
  <b>Comentario:</b>
  <%= @gato.comentario %>
</p>


<%= link_to 'Edit', edit_gato_path(@gato) %> |
<%= link_to 'Back', gatos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gatos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>